### ISSUE TITLE
Wrong config get on middleware

### ISSUE THREAD

**Issue by DwiraSurvivor** [TNkemdilim/adonis-prometheus#1]
I can found wrong config get on middleware :

src/Middlewares/CollectPerformanceMetric.js  line 12

"prometheus.httpMetric.enabled"

must be : 

"prometheus.httpMetric"

**Comment by toksdotdev** [comment]
Apologies for the late response.

Thanks a lot @DwiraSurvivor for raising the issue.

I'll push a fix for this shortly.
